//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Settings/Keyboard.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Keyboard : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Keyboard()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Keyboard"",
    ""maps"": [
        {
            ""name"": ""PlayerMusic"",
            ""id"": ""cf9712b7-b775-421a-a50c-b650ca7265db"",
            ""actions"": [
                {
                    ""name"": ""Key0"",
                    ""type"": ""Button"",
                    ""id"": ""327b2231-4911-43bd-970f-0c62e453b99f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key1"",
                    ""type"": ""Button"",
                    ""id"": ""d958e850-b71a-4139-9464-b127703eaad3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key2"",
                    ""type"": ""Button"",
                    ""id"": ""dcf9f2d2-2d5d-4f13-b0fd-5c412dafd4ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key3"",
                    ""type"": ""Button"",
                    ""id"": ""7b318e14-f3b8-4f71-b507-8d80b1007a7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key4"",
                    ""type"": ""Button"",
                    ""id"": ""1fbf68ef-2ab5-47e0-847e-fd8ba3968209"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key5"",
                    ""type"": ""Button"",
                    ""id"": ""910481b8-3e00-40a4-aeb2-9cfb49e3a9d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key6"",
                    ""type"": ""Button"",
                    ""id"": ""1239454a-a509-4329-9e9c-3660fa730090"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key7"",
                    ""type"": ""Button"",
                    ""id"": ""8df7faea-f53b-4cd2-8d1a-05dc13c35bd2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key8"",
                    ""type"": ""Button"",
                    ""id"": ""2c9df1d5-af30-4760-8227-05302e0986aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key9"",
                    ""type"": ""Button"",
                    ""id"": ""a5956aba-0be5-4271-9818-03c2b95377b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleMovePlay"",
                    ""type"": ""Button"",
                    ""id"": ""8e6f2152-d568-4d61-8633-b5710b3aadec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a151d539-3f6c-41dd-99c9-7097af7f6d0d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d4f1a99-d397-4228-99a2-593c76f61175"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39b151a7-5316-4dd6-bab9-ff179a6a5a43"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fd3c250-b5d2-4a31-8117-ee320d689aa0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e762eedd-8ba8-44b8-b408-0409d4689f36"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c8a3f63-972b-4166-a5bf-5351ff3c5aaf"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""349e8091-8961-4713-8fc8-8bea3c19db79"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3492a68c-8597-49af-84a7-2a8dfd93d36a"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c402a32-5e19-4b77-ae92-0e83b6faa5a2"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86fef40c-b128-4ffb-948b-6d9f0f533294"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dac03a3-9308-4b49-9418-a8d426e5d7ea"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMovePlay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerMove"",
            ""id"": ""91017526-8567-4d03-94ff-ac0f67681da1"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""190dc45b-2f4c-4c9a-b5c8-58e8f47da489"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""19c5ffb5-87b9-4e8f-a498-7cf5d9e1c7a4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerMusic
        m_PlayerMusic = asset.FindActionMap("PlayerMusic", throwIfNotFound: true);
        m_PlayerMusic_Key0 = m_PlayerMusic.FindAction("Key0", throwIfNotFound: true);
        m_PlayerMusic_Key1 = m_PlayerMusic.FindAction("Key1", throwIfNotFound: true);
        m_PlayerMusic_Key2 = m_PlayerMusic.FindAction("Key2", throwIfNotFound: true);
        m_PlayerMusic_Key3 = m_PlayerMusic.FindAction("Key3", throwIfNotFound: true);
        m_PlayerMusic_Key4 = m_PlayerMusic.FindAction("Key4", throwIfNotFound: true);
        m_PlayerMusic_Key5 = m_PlayerMusic.FindAction("Key5", throwIfNotFound: true);
        m_PlayerMusic_Key6 = m_PlayerMusic.FindAction("Key6", throwIfNotFound: true);
        m_PlayerMusic_Key7 = m_PlayerMusic.FindAction("Key7", throwIfNotFound: true);
        m_PlayerMusic_Key8 = m_PlayerMusic.FindAction("Key8", throwIfNotFound: true);
        m_PlayerMusic_Key9 = m_PlayerMusic.FindAction("Key9", throwIfNotFound: true);
        m_PlayerMusic_ToggleMovePlay = m_PlayerMusic.FindAction("ToggleMovePlay", throwIfNotFound: true);
        // PlayerMove
        m_PlayerMove = asset.FindActionMap("PlayerMove", throwIfNotFound: true);
        m_PlayerMove_Newaction = m_PlayerMove.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMusic
    private readonly InputActionMap m_PlayerMusic;
    private IPlayerMusicActions m_PlayerMusicActionsCallbackInterface;
    private readonly InputAction m_PlayerMusic_Key0;
    private readonly InputAction m_PlayerMusic_Key1;
    private readonly InputAction m_PlayerMusic_Key2;
    private readonly InputAction m_PlayerMusic_Key3;
    private readonly InputAction m_PlayerMusic_Key4;
    private readonly InputAction m_PlayerMusic_Key5;
    private readonly InputAction m_PlayerMusic_Key6;
    private readonly InputAction m_PlayerMusic_Key7;
    private readonly InputAction m_PlayerMusic_Key8;
    private readonly InputAction m_PlayerMusic_Key9;
    private readonly InputAction m_PlayerMusic_ToggleMovePlay;
    public struct PlayerMusicActions
    {
        private @Keyboard m_Wrapper;
        public PlayerMusicActions(@Keyboard wrapper) { m_Wrapper = wrapper; }
        public InputAction @Key0 => m_Wrapper.m_PlayerMusic_Key0;
        public InputAction @Key1 => m_Wrapper.m_PlayerMusic_Key1;
        public InputAction @Key2 => m_Wrapper.m_PlayerMusic_Key2;
        public InputAction @Key3 => m_Wrapper.m_PlayerMusic_Key3;
        public InputAction @Key4 => m_Wrapper.m_PlayerMusic_Key4;
        public InputAction @Key5 => m_Wrapper.m_PlayerMusic_Key5;
        public InputAction @Key6 => m_Wrapper.m_PlayerMusic_Key6;
        public InputAction @Key7 => m_Wrapper.m_PlayerMusic_Key7;
        public InputAction @Key8 => m_Wrapper.m_PlayerMusic_Key8;
        public InputAction @Key9 => m_Wrapper.m_PlayerMusic_Key9;
        public InputAction @ToggleMovePlay => m_Wrapper.m_PlayerMusic_ToggleMovePlay;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMusic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMusicActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMusicActions instance)
        {
            if (m_Wrapper.m_PlayerMusicActionsCallbackInterface != null)
            {
                @Key0.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey0;
                @Key0.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey0;
                @Key0.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey0;
                @Key1.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey1;
                @Key1.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey1;
                @Key1.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey1;
                @Key2.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey2;
                @Key2.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey2;
                @Key2.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey2;
                @Key3.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey3;
                @Key3.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey3;
                @Key3.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey3;
                @Key4.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey4;
                @Key4.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey4;
                @Key4.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey4;
                @Key5.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey5;
                @Key5.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey5;
                @Key5.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey5;
                @Key6.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey6;
                @Key6.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey6;
                @Key6.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey6;
                @Key7.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey7;
                @Key7.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey7;
                @Key7.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey7;
                @Key8.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey8;
                @Key8.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey8;
                @Key8.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey8;
                @Key9.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey9;
                @Key9.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey9;
                @Key9.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey9;
                @ToggleMovePlay.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnToggleMovePlay;
                @ToggleMovePlay.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnToggleMovePlay;
                @ToggleMovePlay.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnToggleMovePlay;
            }
            m_Wrapper.m_PlayerMusicActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Key0.started += instance.OnKey0;
                @Key0.performed += instance.OnKey0;
                @Key0.canceled += instance.OnKey0;
                @Key1.started += instance.OnKey1;
                @Key1.performed += instance.OnKey1;
                @Key1.canceled += instance.OnKey1;
                @Key2.started += instance.OnKey2;
                @Key2.performed += instance.OnKey2;
                @Key2.canceled += instance.OnKey2;
                @Key3.started += instance.OnKey3;
                @Key3.performed += instance.OnKey3;
                @Key3.canceled += instance.OnKey3;
                @Key4.started += instance.OnKey4;
                @Key4.performed += instance.OnKey4;
                @Key4.canceled += instance.OnKey4;
                @Key5.started += instance.OnKey5;
                @Key5.performed += instance.OnKey5;
                @Key5.canceled += instance.OnKey5;
                @Key6.started += instance.OnKey6;
                @Key6.performed += instance.OnKey6;
                @Key6.canceled += instance.OnKey6;
                @Key7.started += instance.OnKey7;
                @Key7.performed += instance.OnKey7;
                @Key7.canceled += instance.OnKey7;
                @Key8.started += instance.OnKey8;
                @Key8.performed += instance.OnKey8;
                @Key8.canceled += instance.OnKey8;
                @Key9.started += instance.OnKey9;
                @Key9.performed += instance.OnKey9;
                @Key9.canceled += instance.OnKey9;
                @ToggleMovePlay.started += instance.OnToggleMovePlay;
                @ToggleMovePlay.performed += instance.OnToggleMovePlay;
                @ToggleMovePlay.canceled += instance.OnToggleMovePlay;
            }
        }
    }
    public PlayerMusicActions @PlayerMusic => new PlayerMusicActions(this);

    // PlayerMove
    private readonly InputActionMap m_PlayerMove;
    private IPlayerMoveActions m_PlayerMoveActionsCallbackInterface;
    private readonly InputAction m_PlayerMove_Newaction;
    public struct PlayerMoveActions
    {
        private @Keyboard m_Wrapper;
        public PlayerMoveActions(@Keyboard wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_PlayerMove_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMove; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMoveActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMoveActions instance)
        {
            if (m_Wrapper.m_PlayerMoveActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_PlayerMoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public PlayerMoveActions @PlayerMove => new PlayerMoveActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayerMusicActions
    {
        void OnKey0(InputAction.CallbackContext context);
        void OnKey1(InputAction.CallbackContext context);
        void OnKey2(InputAction.CallbackContext context);
        void OnKey3(InputAction.CallbackContext context);
        void OnKey4(InputAction.CallbackContext context);
        void OnKey5(InputAction.CallbackContext context);
        void OnKey6(InputAction.CallbackContext context);
        void OnKey7(InputAction.CallbackContext context);
        void OnKey8(InputAction.CallbackContext context);
        void OnKey9(InputAction.CallbackContext context);
        void OnToggleMovePlay(InputAction.CallbackContext context);
    }
    public interface IPlayerMoveActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
