//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Settings/Keyboard.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Keyboard : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Keyboard()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Keyboard"",
    ""maps"": [
        {
            ""name"": ""PlayerMusic"",
            ""id"": ""cf9712b7-b775-421a-a50c-b650ca7265db"",
            ""actions"": [
                {
                    ""name"": ""Key0"",
                    ""type"": ""Button"",
                    ""id"": ""327b2231-4911-43bd-970f-0c62e453b99f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key1"",
                    ""type"": ""Button"",
                    ""id"": ""d958e850-b71a-4139-9464-b127703eaad3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key2"",
                    ""type"": ""Button"",
                    ""id"": ""dcf9f2d2-2d5d-4f13-b0fd-5c412dafd4ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key3"",
                    ""type"": ""Button"",
                    ""id"": ""7b318e14-f3b8-4f71-b507-8d80b1007a7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key4"",
                    ""type"": ""Button"",
                    ""id"": ""1fbf68ef-2ab5-47e0-847e-fd8ba3968209"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key5"",
                    ""type"": ""Button"",
                    ""id"": ""910481b8-3e00-40a4-aeb2-9cfb49e3a9d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key6"",
                    ""type"": ""Button"",
                    ""id"": ""1239454a-a509-4329-9e9c-3660fa730090"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key7"",
                    ""type"": ""Button"",
                    ""id"": ""8df7faea-f53b-4cd2-8d1a-05dc13c35bd2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key8"",
                    ""type"": ""Button"",
                    ""id"": ""2c9df1d5-af30-4760-8227-05302e0986aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key9"",
                    ""type"": ""Button"",
                    ""id"": ""a5956aba-0be5-4271-9818-03c2b95377b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleMovePlay"",
                    ""type"": ""Button"",
                    ""id"": ""8e6f2152-d568-4d61-8633-b5710b3aadec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a151d539-3f6c-41dd-99c9-7097af7f6d0d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1629f05e-9400-494a-837a-39ebf7532857"",
                    ""path"": ""<MidiDevice>/note052"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d4f1a99-d397-4228-99a2-593c76f61175"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07b3ff1a-dd9e-42e3-90b1-05618960b1c1"",
                    ""path"": ""<MidiDevice>/note053"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39b151a7-5316-4dd6-bab9-ff179a6a5a43"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""228695a2-30dd-469e-adac-467e2875310b"",
                    ""path"": ""<MidiDevice>/note055"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fd3c250-b5d2-4a31-8117-ee320d689aa0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2d98eac-b0d7-4f2d-a457-d23a76776493"",
                    ""path"": ""<MidiDevice>/note057"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e762eedd-8ba8-44b8-b408-0409d4689f36"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96334ad6-8d63-4bf1-b53d-1260ffe67a8e"",
                    ""path"": ""<MidiDevice>/note059"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c8a3f63-972b-4166-a5bf-5351ff3c5aaf"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd4c0e7f-d925-47db-8407-9db47c0f2786"",
                    ""path"": ""<MidiDevice>/note060"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""349e8091-8961-4713-8fc8-8bea3c19db79"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""126de9a1-122d-48fc-9163-d2181575a087"",
                    ""path"": ""<MidiDevice>/note062"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3492a68c-8597-49af-84a7-2a8dfd93d36a"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71306b76-4b32-4b71-a2fe-b4bacc627c49"",
                    ""path"": ""<MidiDevice>/note064"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c402a32-5e19-4b77-ae92-0e83b6faa5a2"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03e0cf44-297d-454e-ad2e-f1b609f68b4d"",
                    ""path"": ""<MidiDevice>/note065"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86fef40c-b128-4ffb-948b-6d9f0f533294"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1e6a883-39c9-462a-8b09-394a59f3f70c"",
                    ""path"": ""<MidiDevice>/note067"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dac03a3-9308-4b49-9418-a8d426e5d7ea"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMovePlay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95f6edda-b29e-4e68-9cda-78faf99b1306"",
                    ""path"": ""<MidiDevice>/note061"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMovePlay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerMove"",
            ""id"": ""91017526-8567-4d03-94ff-ac0f67681da1"",
            ""actions"": [
                {
                    ""name"": ""Echolocation"",
                    ""type"": ""Button"",
                    ""id"": ""190dc45b-2f4c-4c9a-b5c8-58e8f47da489"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleMovePlay"",
                    ""type"": ""Button"",
                    ""id"": ""d887c941-6910-4730-819e-ebd27698237c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move0"",
                    ""type"": ""Button"",
                    ""id"": ""0d8630ae-a743-4da6-9dfe-503002ca58a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move1"",
                    ""type"": ""Button"",
                    ""id"": ""e9fe65b0-baaf-4700-8b41-d46f2267305f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move2"",
                    ""type"": ""Button"",
                    ""id"": ""6de87add-2b42-48d1-b8e0-78602b175c2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move3"",
                    ""type"": ""Button"",
                    ""id"": ""e4a12c78-4e86-4378-999f-1d50efc2debc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RestartGame"",
                    ""type"": ""Button"",
                    ""id"": ""8d1881f6-2d6c-47c1-a0e6-eb862ce96ff3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""19c5ffb5-87b9-4e8f-a498-7cf5d9e1c7a4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Echolocation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""818c8923-88df-4470-a347-80e885071721"",
                    ""path"": ""<MidiDevice>/note055"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Echolocation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9970df39-c2b3-48f4-9c16-d2b28cc34676"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55aef4e1-8047-4eb6-bb45-f0e3e57eb73c"",
                    ""path"": ""<MidiDevice>/note052"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59cf5aec-c857-4f62-9657-7aca2d2a7b66"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6949bbdc-ed73-4773-8310-3dc892ad700d"",
                    ""path"": ""<MidiDevice>/note053"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ae93e79-31d9-49ea-80a3-a0e82d0f41e7"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47a0f62e-542b-4aba-8104-0c728a7a14ef"",
                    ""path"": ""<MidiDevice>/note057"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b017b86e-553e-44b9-96f5-7e296eb98eb1"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32409d57-baac-4823-a730-402a2a0fa709"",
                    ""path"": ""<MidiDevice>/note059"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f303100-a9b1-48f1-8a21-d8039696e90b"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMovePlay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09ac21e9-27c8-4688-ba6a-ede72dfe22c9"",
                    ""path"": ""<MidiDevice>/note061"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMovePlay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ad96518-51e2-4aca-8a11-3981e4a4670c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RestartGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerMusic
        m_PlayerMusic = asset.FindActionMap("PlayerMusic", throwIfNotFound: true);
        m_PlayerMusic_Key0 = m_PlayerMusic.FindAction("Key0", throwIfNotFound: true);
        m_PlayerMusic_Key1 = m_PlayerMusic.FindAction("Key1", throwIfNotFound: true);
        m_PlayerMusic_Key2 = m_PlayerMusic.FindAction("Key2", throwIfNotFound: true);
        m_PlayerMusic_Key3 = m_PlayerMusic.FindAction("Key3", throwIfNotFound: true);
        m_PlayerMusic_Key4 = m_PlayerMusic.FindAction("Key4", throwIfNotFound: true);
        m_PlayerMusic_Key5 = m_PlayerMusic.FindAction("Key5", throwIfNotFound: true);
        m_PlayerMusic_Key6 = m_PlayerMusic.FindAction("Key6", throwIfNotFound: true);
        m_PlayerMusic_Key7 = m_PlayerMusic.FindAction("Key7", throwIfNotFound: true);
        m_PlayerMusic_Key8 = m_PlayerMusic.FindAction("Key8", throwIfNotFound: true);
        m_PlayerMusic_Key9 = m_PlayerMusic.FindAction("Key9", throwIfNotFound: true);
        m_PlayerMusic_ToggleMovePlay = m_PlayerMusic.FindAction("ToggleMovePlay", throwIfNotFound: true);
        // PlayerMove
        m_PlayerMove = asset.FindActionMap("PlayerMove", throwIfNotFound: true);
        m_PlayerMove_Echolocation = m_PlayerMove.FindAction("Echolocation", throwIfNotFound: true);
        m_PlayerMove_ToggleMovePlay = m_PlayerMove.FindAction("ToggleMovePlay", throwIfNotFound: true);
        m_PlayerMove_Move0 = m_PlayerMove.FindAction("Move0", throwIfNotFound: true);
        m_PlayerMove_Move1 = m_PlayerMove.FindAction("Move1", throwIfNotFound: true);
        m_PlayerMove_Move2 = m_PlayerMove.FindAction("Move2", throwIfNotFound: true);
        m_PlayerMove_Move3 = m_PlayerMove.FindAction("Move3", throwIfNotFound: true);
        m_PlayerMove_RestartGame = m_PlayerMove.FindAction("RestartGame", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMusic
    private readonly InputActionMap m_PlayerMusic;
    private IPlayerMusicActions m_PlayerMusicActionsCallbackInterface;
    private readonly InputAction m_PlayerMusic_Key0;
    private readonly InputAction m_PlayerMusic_Key1;
    private readonly InputAction m_PlayerMusic_Key2;
    private readonly InputAction m_PlayerMusic_Key3;
    private readonly InputAction m_PlayerMusic_Key4;
    private readonly InputAction m_PlayerMusic_Key5;
    private readonly InputAction m_PlayerMusic_Key6;
    private readonly InputAction m_PlayerMusic_Key7;
    private readonly InputAction m_PlayerMusic_Key8;
    private readonly InputAction m_PlayerMusic_Key9;
    private readonly InputAction m_PlayerMusic_ToggleMovePlay;
    public struct PlayerMusicActions
    {
        private @Keyboard m_Wrapper;
        public PlayerMusicActions(@Keyboard wrapper) { m_Wrapper = wrapper; }
        public InputAction @Key0 => m_Wrapper.m_PlayerMusic_Key0;
        public InputAction @Key1 => m_Wrapper.m_PlayerMusic_Key1;
        public InputAction @Key2 => m_Wrapper.m_PlayerMusic_Key2;
        public InputAction @Key3 => m_Wrapper.m_PlayerMusic_Key3;
        public InputAction @Key4 => m_Wrapper.m_PlayerMusic_Key4;
        public InputAction @Key5 => m_Wrapper.m_PlayerMusic_Key5;
        public InputAction @Key6 => m_Wrapper.m_PlayerMusic_Key6;
        public InputAction @Key7 => m_Wrapper.m_PlayerMusic_Key7;
        public InputAction @Key8 => m_Wrapper.m_PlayerMusic_Key8;
        public InputAction @Key9 => m_Wrapper.m_PlayerMusic_Key9;
        public InputAction @ToggleMovePlay => m_Wrapper.m_PlayerMusic_ToggleMovePlay;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMusic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMusicActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMusicActions instance)
        {
            if (m_Wrapper.m_PlayerMusicActionsCallbackInterface != null)
            {
                @Key0.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey0;
                @Key0.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey0;
                @Key0.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey0;
                @Key1.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey1;
                @Key1.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey1;
                @Key1.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey1;
                @Key2.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey2;
                @Key2.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey2;
                @Key2.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey2;
                @Key3.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey3;
                @Key3.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey3;
                @Key3.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey3;
                @Key4.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey4;
                @Key4.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey4;
                @Key4.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey4;
                @Key5.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey5;
                @Key5.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey5;
                @Key5.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey5;
                @Key6.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey6;
                @Key6.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey6;
                @Key6.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey6;
                @Key7.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey7;
                @Key7.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey7;
                @Key7.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey7;
                @Key8.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey8;
                @Key8.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey8;
                @Key8.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey8;
                @Key9.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey9;
                @Key9.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey9;
                @Key9.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnKey9;
                @ToggleMovePlay.started -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnToggleMovePlay;
                @ToggleMovePlay.performed -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnToggleMovePlay;
                @ToggleMovePlay.canceled -= m_Wrapper.m_PlayerMusicActionsCallbackInterface.OnToggleMovePlay;
            }
            m_Wrapper.m_PlayerMusicActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Key0.started += instance.OnKey0;
                @Key0.performed += instance.OnKey0;
                @Key0.canceled += instance.OnKey0;
                @Key1.started += instance.OnKey1;
                @Key1.performed += instance.OnKey1;
                @Key1.canceled += instance.OnKey1;
                @Key2.started += instance.OnKey2;
                @Key2.performed += instance.OnKey2;
                @Key2.canceled += instance.OnKey2;
                @Key3.started += instance.OnKey3;
                @Key3.performed += instance.OnKey3;
                @Key3.canceled += instance.OnKey3;
                @Key4.started += instance.OnKey4;
                @Key4.performed += instance.OnKey4;
                @Key4.canceled += instance.OnKey4;
                @Key5.started += instance.OnKey5;
                @Key5.performed += instance.OnKey5;
                @Key5.canceled += instance.OnKey5;
                @Key6.started += instance.OnKey6;
                @Key6.performed += instance.OnKey6;
                @Key6.canceled += instance.OnKey6;
                @Key7.started += instance.OnKey7;
                @Key7.performed += instance.OnKey7;
                @Key7.canceled += instance.OnKey7;
                @Key8.started += instance.OnKey8;
                @Key8.performed += instance.OnKey8;
                @Key8.canceled += instance.OnKey8;
                @Key9.started += instance.OnKey9;
                @Key9.performed += instance.OnKey9;
                @Key9.canceled += instance.OnKey9;
                @ToggleMovePlay.started += instance.OnToggleMovePlay;
                @ToggleMovePlay.performed += instance.OnToggleMovePlay;
                @ToggleMovePlay.canceled += instance.OnToggleMovePlay;
            }
        }
    }
    public PlayerMusicActions @PlayerMusic => new PlayerMusicActions(this);

    // PlayerMove
    private readonly InputActionMap m_PlayerMove;
    private IPlayerMoveActions m_PlayerMoveActionsCallbackInterface;
    private readonly InputAction m_PlayerMove_Echolocation;
    private readonly InputAction m_PlayerMove_ToggleMovePlay;
    private readonly InputAction m_PlayerMove_Move0;
    private readonly InputAction m_PlayerMove_Move1;
    private readonly InputAction m_PlayerMove_Move2;
    private readonly InputAction m_PlayerMove_Move3;
    private readonly InputAction m_PlayerMove_RestartGame;
    public struct PlayerMoveActions
    {
        private @Keyboard m_Wrapper;
        public PlayerMoveActions(@Keyboard wrapper) { m_Wrapper = wrapper; }
        public InputAction @Echolocation => m_Wrapper.m_PlayerMove_Echolocation;
        public InputAction @ToggleMovePlay => m_Wrapper.m_PlayerMove_ToggleMovePlay;
        public InputAction @Move0 => m_Wrapper.m_PlayerMove_Move0;
        public InputAction @Move1 => m_Wrapper.m_PlayerMove_Move1;
        public InputAction @Move2 => m_Wrapper.m_PlayerMove_Move2;
        public InputAction @Move3 => m_Wrapper.m_PlayerMove_Move3;
        public InputAction @RestartGame => m_Wrapper.m_PlayerMove_RestartGame;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMove; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMoveActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMoveActions instance)
        {
            if (m_Wrapper.m_PlayerMoveActionsCallbackInterface != null)
            {
                @Echolocation.started -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnEcholocation;
                @Echolocation.performed -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnEcholocation;
                @Echolocation.canceled -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnEcholocation;
                @ToggleMovePlay.started -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnToggleMovePlay;
                @ToggleMovePlay.performed -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnToggleMovePlay;
                @ToggleMovePlay.canceled -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnToggleMovePlay;
                @Move0.started -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove0;
                @Move0.performed -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove0;
                @Move0.canceled -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove0;
                @Move1.started -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove1;
                @Move1.performed -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove1;
                @Move1.canceled -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove1;
                @Move2.started -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove2;
                @Move2.performed -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove2;
                @Move2.canceled -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove2;
                @Move3.started -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove3;
                @Move3.performed -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove3;
                @Move3.canceled -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMove3;
                @RestartGame.started -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnRestartGame;
                @RestartGame.performed -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnRestartGame;
                @RestartGame.canceled -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnRestartGame;
            }
            m_Wrapper.m_PlayerMoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Echolocation.started += instance.OnEcholocation;
                @Echolocation.performed += instance.OnEcholocation;
                @Echolocation.canceled += instance.OnEcholocation;
                @ToggleMovePlay.started += instance.OnToggleMovePlay;
                @ToggleMovePlay.performed += instance.OnToggleMovePlay;
                @ToggleMovePlay.canceled += instance.OnToggleMovePlay;
                @Move0.started += instance.OnMove0;
                @Move0.performed += instance.OnMove0;
                @Move0.canceled += instance.OnMove0;
                @Move1.started += instance.OnMove1;
                @Move1.performed += instance.OnMove1;
                @Move1.canceled += instance.OnMove1;
                @Move2.started += instance.OnMove2;
                @Move2.performed += instance.OnMove2;
                @Move2.canceled += instance.OnMove2;
                @Move3.started += instance.OnMove3;
                @Move3.performed += instance.OnMove3;
                @Move3.canceled += instance.OnMove3;
                @RestartGame.started += instance.OnRestartGame;
                @RestartGame.performed += instance.OnRestartGame;
                @RestartGame.canceled += instance.OnRestartGame;
            }
        }
    }
    public PlayerMoveActions @PlayerMove => new PlayerMoveActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayerMusicActions
    {
        void OnKey0(InputAction.CallbackContext context);
        void OnKey1(InputAction.CallbackContext context);
        void OnKey2(InputAction.CallbackContext context);
        void OnKey3(InputAction.CallbackContext context);
        void OnKey4(InputAction.CallbackContext context);
        void OnKey5(InputAction.CallbackContext context);
        void OnKey6(InputAction.CallbackContext context);
        void OnKey7(InputAction.CallbackContext context);
        void OnKey8(InputAction.CallbackContext context);
        void OnKey9(InputAction.CallbackContext context);
        void OnToggleMovePlay(InputAction.CallbackContext context);
    }
    public interface IPlayerMoveActions
    {
        void OnEcholocation(InputAction.CallbackContext context);
        void OnToggleMovePlay(InputAction.CallbackContext context);
        void OnMove0(InputAction.CallbackContext context);
        void OnMove1(InputAction.CallbackContext context);
        void OnMove2(InputAction.CallbackContext context);
        void OnMove3(InputAction.CallbackContext context);
        void OnRestartGame(InputAction.CallbackContext context);
    }
}
